In [ ]:
import pandas as pd
import numpy as np

:

In [ ]:
DATA_PATH = "../data/raw/"
os.listdir(DATA_PATH)

['Books.csv', 'google_books_dataset.csv', 'Ratings.csv', 'Users.csv']

In [6]:
books = pd.read_csv(DATA_PATH + "Books.csv")
users = pd.read_csv(DATA_PATH + "Users.csv")
ratings = pd.read_csv(DATA_PATH + "Ratings.csv")
google_books = pd.read_csv(DATA_PATH + "google_books_dataset.csv")

C:\Users\anshu\AppData\Local\Temp\ipykernel_3304\2654247786.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(DATA_PATH + "Books.csv")

In [7]:
print("Books Shape:", books.shape)
print("Users Shape:", users.shape)
print("Ratings Shape:", ratings.shape)
print("Google Books Shape:", google_books.shape)

Books Shape: (271360, 8)
Users Shape: (278858, 3)
Ratings Shape: (1149780, 3)
Google Books Shape: (15147, 21)

In [8]:
print("BOOKS COLUMNS")
print(books.columns.tolist())

print("\nUSERS COLUMNS")
print(users.columns.tolist())

print("\nRATINGS COLUMNS")
print(ratings.columns.tolist())

print("\nGOOGLE BOOKS COLUMNS")
print(google_books.columns.tolist())

BOOKS COLUMNS
['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M', 'Image-URL-L']

USERS COLUMNS
['User-ID', 'Location', 'Age']

RATINGS COLUMNS
['User-ID', 'ISBN', 'Book-Rating']

GOOGLE BOOKS COLUMNS
['book_id', 'title', 'subtitle', 'authors', 'publisher', 'published_date', 'description', 'page_count', 'categories', 'average_rating', 'ratings_count', 'language', 'preview_link', 'info_link', 'isbn_13', 'isbn_10', 'list_price', 'currency', 'buyable', 'search_category', 'thumbnail']

In [ ]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [11]:
google_books.head()

,book_id,title,subtitle,authors,publisher,published_date,description,page_count,categories,average_rating,...,language,preview_link,info_link,isbn_13,isbn_10,list_price,currency,buyable,search_category,thumbnail
0,LR_VDQAAQBAJ,Bestsellers,"The Path (bestsellers, free bestsellers, bests...","Ivan King, bestsellers",bestsellers,2017-01-04,"Hear What the Critics are Saying ""Wow, what an...",70.0,Young Adult Fiction,NaN,...,en,http://books.google.com/books?id=LR_VDQAAQBAJ&...,https://play.google.com/store/books/details?id...,NaN,NaN,12.99,USD,True,fiction bestsellers,http://books.google.com/books/content?id=LR_VD...
1,WcjTDQAAQBAJ,Bestsellers,"Hell: A Place Without Hope (bestseller books, ...","Ivan King, bestsellers",bestsellers,2017-01-03,"Hear What the Critics are Saying Wow, very ins...",32.0,Comics & Graphic Novels,NaN,...,en,http://books.google.com/books?id=WcjTDQAAQBAJ&...,https://play.google.com/store/books/details?id...,NaN,NaN,9.99,USD,True,fiction bestsellers,http://books.google.com/books/content?id=WcjTD...
2,4fXUDAAAQBAJ,The Bestseller Code,Anatomy of the Blockbuster Novel,"Jodie Archer, Matthew L. Jockers",Macmillan,2016-09-20,"""What if there was an algorithm that could pre...",253.0,Business & Economics,NaN,...,en,http://books.google.com/books?id=4fXUDAAAQBAJ&...,http://books.google.com/books?id=4fXUDAAAQBAJ&...,9.781250e+12,1250088275,NaN,NaN,False,fiction bestsellers,http://books.google.com/books/content?id=4fXUD...
3,yIVuDwAAQBAJ,Bestseller,A Century of America's Favorite Books,Robert McParland,Bloomsbury Publishing PLC,2018-12-15,Whether curled up on a sofa with a good myster...,335.0,Literary Criticism,NaN,...,en,http://books.google.com/books?id=yIVuDwAAQBAJ&...,https://play.google.com/store/books/details?id...,9.781538e+12,1538110008,40.50,USD,True,fiction bestsellers,http://books.google.com/books/content?id=yIVuD...
4,2JHXwAEACAAJ,Bestsellers: Popular Fiction since 1900,NaN,C. Bloom,Palgrave Macmillan,2002-07-09,This guide and reference work of all of the be...,306.0,Literary Criticism,NaN,...,en,http://books.google.com/books?id=2JHXwAEACAAJ&...,http://books.google.com/books?id=2JHXwAEACAAJ&...,9.780334e+12,0333687426,NaN,NaN,False,fiction bestsellers,http://books.google.com/books/content?id=2JHXw...

In [12]:
print("Books ISBN dtype:")
print(books["ISBN"].dtype)

print("\nGoogle ISBN-10 dtype:")
print(google_books["isbn_10"].dtype)

print("\nGoogle ISBN-13 dtype:")
print(google_books["isbn_13"].dtype)

Books ISBN dtype:
str

Google ISBN-10 dtype:
str

Google ISBN-13 dtype:
float64

In [13]:
print("Missing ISBN-10:")
print(google_books["isbn_10"].isna().sum())

print("\nMissing ISBN-13:")
print(google_books["isbn_13"].isna().sum())

Missing ISBN-10:
8026

Missing ISBN-13:
7764

In [14]:
print("Book-Crossing ISBN Examples")
print(books["ISBN"].head())

print("\nGoogle ISBN-10 Examples")
print(google_books["isbn_10"].head())

print("\nGoogle ISBN-13 Examples")
print(google_books["isbn_13"].head())

Book-Crossing ISBN Examples
0    0195153448
1    0002005018
2    0060973129
3    0374157065
4    0393045218
Name: ISBN, dtype: str

Google ISBN-10 Examples
0           NaN
1           NaN
2    1250088275
3    1538110008
4    0333687426
Name: isbn_10, dtype: str

Google ISBN-13 Examples
0             NaN
1             NaN
2    9.781250e+12
3    9.781538e+12
4    9.780334e+12
Name: isbn_13, dtype: float64

In [15]:
bx_isbn = set(books["ISBN"])

google_isbn10 = set(
    google_books["isbn_10"].dropna()
)

In [16]:
common_isbn = bx_isbn.intersection(
    google_isbn10
)

print("Matching ISBNs:", len(common_isbn))

Matching ISBNs: 153

In [17]:
books[
    ["Book-Title", "Book-Author"]
].head(10)

                                          Book-Title           Book-Author
0                                Classical Mythology    Mark P. O. Morford
1                                       Clara Callan  Richard Bruce Wright
2                               Decision in Normandy          Carlo D'Este
3  Flu: The Story of the Great Influenza Pandemic...      Gina Bari Kolata
4                             The Mummies of Urumchi       E. J. W. Barber
5                             The Kitchen God's Wife               Amy Tan
6  What If?: The World's Foremost Military Histor...         Robert Cowley
7                                    PLEADING GUILTY           Scott Turow
8  Under the Black Flag: The Romance and the Real...       David Cordingly
9            Where You'll Find Me: And Other Stories           Ann Beattie

In [18]:
google_books[
    ["title", "authors"]
].head(10)

,title,authors
0,Bestsellers,"Ivan King, bestsellers"
1,Bestsellers,"Ivan King, bestsellers"
2,The Bestseller Code,"Jodie Archer, Matthew L. Jockers"
3,Bestseller,Robert McParland
4,Bestsellers: Popular Fiction since 1900,C. Bloom
5,Hype,"Jon Helgason, Sara Kärrholm, Ann Steiner"
6,"Bestsellers, 1979-1983",Library of Congress. National Library Service ...
7,Mary Higgins Clark,Mary Higgins Clark
8,Bestsellers,John Sutherland
9,The Publishers Weekly,NaN

In [19]:
bx_titles = set(
    books["Book-Title"]
    .str.lower()
    .str.strip()
)

google_titles = set(
    google_books["title"]
    .str.lower()
    .str.strip()
    .dropna()
)

In [20]:
common_titles = bx_titles.intersection(
    google_titles
)

print("Matching Titles:", len(common_titles))

Matching Titles: 610

In [21]:
list(common_titles)[:20]

['a painted house',
 'science of desire',
 'america online for dummies quick reference',
 'murder on the links',
 'sisters',
 'blake',
 'good omens',
 'photography your way',
 'we',
 'how to stop worrying and start living',
 'prey',
 'daughter of fortune',
 'survivor',
 'calculus with analytic geometry',
 'word',
 'gourmet vegetarian feasts',
 'hogfather',
 'neverwhere',
 'no greater love',
 'misery']

In [22]:
books["Book-Author"].sample(10, random_state=42)

103740          Jesse Sheidlower
195299    Hans Werner Kettenbach
161791             Marella Sands
184788             Mary McCarthy
161347             Ann M. Martin
73355                Donna Vitek
154424        Albert, Schweitzer
64568             Ann McAllister
31891               Linda Howard
238604                Joe Garner
Name: Book-Author, dtype: str

In [23]:
google_books["authors"].sample(10, random_state=42)

566                    Jeff Herman
13567                          NaN
2085                           NaN
10569                          NaN
9898                  Andrew Flach
8748                           NaN
3547        Josephus Nelson Larned
13058    Wei-Chi Wu, Wai-Ching Lam
3623                       A. Hall
2250                Peter Robinson
Name: authors, dtype: str

In [24]:
title_matches = books[
    books["Book-Title"].str.lower().isin(common_titles)
][["Book-Title", "Book-Author"]]

title_matches.head(20)

              Book-Title        Book-Author
18         The Testament       John Grisham
52     The Street Lawyer       JOHN GRISHAM
205      Four Blind Mice    James Patterson
221            Bleachers       John Grisham
237      Deception Point          Dan Brown
255        Thief of Time    Terry Pratchett
305      A Painted House       John Grisham
313            Symposium      Paul Woodruff
361             The Firm       John Grisham
412      Life Before Man    Margaret Atwood
414     The Robber Bride    Margaret Atwood
456             The Firm       John Grisham
495        The Messenger     JOSEPH GIRZONE
519  Daughter of Fortune     Isabel Allende
572            11th Hour  Bradley Warshauer
574        Brazen Virtue       Nora Roberts
584          River's End       Nora Roberts
585        Summer Island     KRISTIN HANNAH
588    The Street Lawyer       John Grisham
589          The Chamber       John Grisham

In [25]:
print("Missing Titles:")
print(google_books["title"].isna().sum())

print("\nMissing Authors:")
print(google_books["authors"].isna().sum())

print("\nMissing Descriptions:")
print(google_books["description"].isna().sum())

print("\nMissing Categories:")
print(google_books["categories"].isna().sum())

Missing Titles:
8

Missing Authors:
3525

Missing Descriptions:
6796

Missing Categories:
2452

In [40]:
import re

def normalize_text(text):

    if pd.isna(text):
        return ""

    text = str(text).lower()

    # Remove apostrophes entirely
    text = text.replace("'", "")

    # Replace remaining punctuation with spaces
    text = re.sub(r"[^a-z0-9\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [41]:
examples = [
    "The Kitchen God's Wife",
    "THE FIRM",
    " Harry   Potter ",
    "Nora Roberts!",
    np.nan
]

for x in examples:
    print(x, " --> ", normalize_text(x))

The Kitchen God's Wife  -->  the kitchen gods wife
THE FIRM  -->  the firm
 Harry   Potter   -->  harry potter
Nora Roberts!  -->  nora roberts
nan  -->

In [42]:
books["title_clean"] = books["Book-Title"].apply(
    normalize_text
)

google_books["title_clean"] = google_books["title"].apply(
    normalize_text
)

In [43]:
def extract_primary_author(author_text):

    if pd.isna(author_text):
        return ""

    return str(author_text).split(",")[0]

In [44]:
books["author_clean"] = books["Book-Author"].apply(
    normalize_text
)

google_books["author_clean"] = (
    google_books["authors"]
    .apply(extract_primary_author)
    .apply(normalize_text)
)

In [45]:
books[
    ["Book-Title", "title_clean",
     "Book-Author", "author_clean"]
].head()

,Book-Title,title_clean,Book-Author,author_clean
0,Classical Mythology,classical mythology,Mark P. O. Morford,mark p o morford
1,Clara Callan,clara callan,Richard Bruce Wright,richard bruce wright
2,Decision in Normandy,decision in normandy,Carlo D'Este,carlo deste
3,Flu: The Story of the Great Influenza Pandemic...,flu the story of the great influenza pandemic ...,Gina Bari Kolata,gina bari kolata
4,The Mummies of Urumchi,the mummies of urumchi,E. J. W. Barber,e j w barber

In [46]:
google_books[
    ["title", "title_clean",
     "authors", "author_clean"]
].head()

,title,title_clean,authors,author_clean
0,Bestsellers,bestsellers,"Ivan King, bestsellers",ivan king
1,Bestsellers,bestsellers,"Ivan King, bestsellers",ivan king
2,The Bestseller Code,the bestseller code,"Jodie Archer, Matthew L. Jockers",jodie archer
3,Bestseller,bestseller,Robert McParland,robert mcparland
4,Bestsellers: Popular Fiction since 1900,bestsellers popular fiction since 1900,C. Bloom,c bloom

In [47]:
books["match_key"] = (
    books["title_clean"]
    + "_"
    + books["author_clean"]
)

google_books["match_key"] = (
    google_books["title_clean"]
    + "_"
    + google_books["author_clean"]
)

In [48]:
bx_keys = set(books["match_key"])

google_keys = set(google_books["match_key"])

common_keys = bx_keys.intersection(google_keys)

print("Matching Title+Author Keys:", len(common_keys))

Matching Title+Author Keys: 314

In [49]:
matched_books = books[
    books["match_key"].isin(common_keys)
][[
    "Book-Title",
    "Book-Author",
    "match_key"
]]

matched_books.head(20)

,Book-Title,Book-Author,match_key
18,The Testament,John Grisham,the testament_john grisham
52,The Street Lawyer,JOHN GRISHAM,the street lawyer_john grisham
205,Four Blind Mice,James Patterson,four blind mice_james patterson
221,Bleachers,John Grisham,bleachers_john grisham
237,Deception Point,Dan Brown,deception point_dan brown
255,Thief of Time,Terry Pratchett,thief of time_terry pratchett
305,A Painted House,John Grisham,a painted house_john grisham
361,The Firm,John Grisham,the firm_john grisham
412,Life Before Man,Margaret Atwood,life before man_margaret atwood
414,The Robber Bride,Margaret Atwood,the robber bride_margaret atwood
456,The Firm,John Grisham,the firm_john grisham
519,Daughter of Fortune,Isabel Allende,daughter of fortune_isabel allende
574,Brazen Virtue,Nora Roberts,brazen virtue_nora roberts
584,River's End,Nora Roberts,rivers end_nora roberts
585,Summer Island,KRISTIN HANNAH,summer island_kristin hannah
588,The Street Lawyer,John Grisham,the street lawyer_john grisham
589,The Chamber,John Grisham,the chamber_john grisham
592,The Partner,John Grisham,the partner_john grisham
748,The Da Vinci Code,Dan Brown,the da vinci code_dan brown
786,Suzanne's Diary for Nicholas,James Patterson,suzannes diary for nicholas_james patterson

In [51]:
title_overlap = books.merge(
    google_books,
    on="title_clean",
    suffixes=("_bx", "_google")
)

In [52]:
title_overlap[
    title_overlap["author_clean_bx"]
    != title_overlap["author_clean_google"]
][[
    "Book-Title",
    "Book-Author",
    "authors"
]].head(20)

              Book-Title        Book-Author                            authors
12             Symposium      Paul Woodruff                                NaN
19         The Messenger     JOSEPH GIRZONE                                NaN
21             11th Hour  Bradley Warshauer     James Patterson, Maxine Paetro
30                 Three         Ted Dekker                     Valérie Perrin
31                 Blink         Ted Dekker                   Malcolm Gladwell
32                 Blink         Ted Dekker                   Malcolm Gladwell
33                 Blink         Ted Dekker                   Malcolm Gladwell
34                 Blink         Ted Dekker    Malcolm Gladwell, Thomas Rydahl
35                 Blink         Ted Dekker                   Malcolm Gladwell
36                 Blink         Ted Dekker                   Malcolm Gladwell
37                Echoes       Maeve Binchy                     Danielle Steel
49     Wuthering Heights       EMILY BRONTE                  Graham Holderness
51     Wuthering Heights       Emily Bronte                  Graham Holderness
57  The Distance Between      Eliza Osborne                      Mike McIntyre
61         Cooking Light  Susan M. McIntosh                                NaN
77      The Simple Truth     David Baldacci                      Philip Levine
78     Wuthering Heights       Emily Bronte                  Graham Holderness
79            After Dark       Jayne Castle                    Haruki Murakami
80            After Dark       Jayne Castle                    Haruki Murakami
82       Now You See Her       Linda Howard  James Patterson, Michael Ledwidge

In [54]:
matched_df = books.merge(
    google_books,
    on="match_key",
    how="inner",
    suffixes=("_bx", "_google")
)

print("Matched rows:", matched_df.shape[0])

matched_df[
    [
        "Book-Title",
        "Book-Author",
        "title",
        "authors"
    ]
].head(20)

Matched rows: 1096

,Book-Title,Book-Author,title,authors
0,The Testament,John Grisham,The Testament,John Grisham
1,The Testament,John Grisham,The Testament,John Grisham
2,The Street Lawyer,JOHN GRISHAM,The Street Lawyer,John Grisham
3,The Street Lawyer,JOHN GRISHAM,The Street Lawyer,John Grisham
4,Four Blind Mice,James Patterson,Four Blind Mice,James Patterson
5,Bleachers,John Grisham,Bleachers,John Grisham
6,Deception Point,Dan Brown,Deception Point,Dan Brown
7,Deception Point,Dan Brown,Deception Point/डिसेप्शन प्वाइंट,Dan Brown/डैन ब्राउन
8,Deception Point,Dan Brown,Deception point,Dan Brown
9,Thief of Time,Terry Pratchett,Thief of Time,Terry Pratchett
10,A Painted House,John Grisham,A Painted House,John Grisham
11,A Painted House,John Grisham,A Painted House,John Grisham
12,The Firm,John Grisham,The Firm,John Grisham
13,The Firm,John Grisham,The Firm,John Grisham
14,Life Before Man,Margaret Atwood,Life Before Man,Margaret Atwood
15,The Robber Bride,Margaret Atwood,The Robber Bride,Margaret Atwood
16,The Firm,John Grisham,The Firm,John Grisham
17,The Firm,John Grisham,The Firm,John Grisham
18,Daughter of Fortune,Isabel Allende,Daughter of Fortune,Isabel Allende
19,Brazen Virtue,Nora Roberts,Brazen Virtue,Nora Roberts

In [55]:
google_books["match_key"].duplicated().sum()

np.int64(1444)

In [56]:
google_books["match_key"].value_counts().head(20)

match_key
the publishers weekly_                                                                   25
_                                                                                        17
think and grow rich_napoleon hill                                                        17
california court of appeal 2nd appellate district records and briefs_california state    11
library of congress catalogs_library of congress                                         11
parliamentary debates hansard_great britain parliament house of commons                  11
library of congress subject headings_library of congress                                 10
the massachusetts register_                                                               9
bulletin_                                                                                 9
the bookman_                                                                              8
good housekeeping_                                                                        8
national union catalog_                                                                   8
library journal_                                                                          8
the athenaeum_                                                                            8
the parliamentary debates official report_great britain parliament house of commons       8
proceedings_                                                                              8
the mysterious affair at styles_agatha christie                                           8
current literature_                                                                       7
the spectator_                                                                            7
annual register_university of chicago                                                     7
Name: count, dtype: int64

In [57]:
google_books["author_clean"].eq("").sum()

np.int64(3535)

In [58]:
matched_df["author_clean_google"].eq("").sum()

np.int64(0)

In [59]:
matched_df["match_key"].value_counts().head(20)

match_key
think and grow rich_napoleon hill                        68
beloved_toni morrison                                    50
the mysterious affair at styles_agatha christie          24
carrie_stephen king                                      24
and then there were none_agatha christie                 21
king lear_william shakespeare                            20
the da vinci code_dan brown                              18
dracula_bram stoker                                      17
the handmaids tale_margaret atwood                       16
alias grace_margaret atwood                              16
the firm_john grisham                                    14
misery_stephen king                                      14
coraline_neil gaiman                                     14
a time to kill_john grisham                              12
the runaway jury_john grisham                            12
how to win friends and influence people_dale carnegie    12
1984_george orwell                                       11
the testament_john grisham                               10
the street lawyer_john grisham                           10
a painted house_john grisham                             10
Name: count, dtype: int64

In [60]:
matched_df["match_key"].nunique()

314

In [61]:
print("Matched rows:", matched_df.shape[0])

print("Unique matched books:",
      matched_df["match_key"].nunique())

Matched rows: 1096
Unique matched books: 314

In [62]:
google_books["metadata_score"] = (
    google_books["description"].notna().astype(int)
    + google_books["categories"].notna().astype(int)
    + google_books["language"].notna().astype(int)
    + google_books["page_count"].notna().astype(int)
    + google_books["thumbnail"].notna().astype(int)
)

In [63]:
google_best = (
    google_books
    .sort_values(
        "metadata_score",
        ascending=False
    )
    .drop_duplicates(
        subset="match_key",
        keep="first"
    )
)

In [64]:
print("Original Google Books:", google_books.shape)

print("After Deduplication:", google_best.shape)

Original Google Books: (15147, 25)
After Deduplication: (13703, 25)

In [65]:
google_best["match_key"].duplicated().sum()

np.int64(0)

In [66]:
google_selected = google_best[
    [
        "match_key",
        "description",
        "categories",
        "language",
        "page_count",
        "thumbnail"
    ]
]

In [67]:
books_master = books.merge(
    google_selected,
    on="match_key",
    how="left"
)

In [68]:
print("Books Shape:", books.shape)

print("Books Master Shape:", books_master.shape)

Books Shape: (271360, 11)
Books Master Shape: (271360, 16)

In [70]:
books_master["description"].notna().sum()

np.int64(692)

In [71]:
books_master["categories"].notna().sum()

np.int64(700)

In [72]:
enriched_books = books_master[
    books_master["description"].notna()
]

print(enriched_books.shape)

(692, 16)

In [73]:
enriched_books[
    [
        "Book-Title",
        "Book-Author",
        "categories",
        "language"
    ]
].sample(20, random_state=42)

,Book-Title,Book-Author,categories,language
80482,The Summons,John Grisham,Fiction,en
246443,Mindfulness Meditation for Everyday Life,Jon Kabat-Zinn,Attention,en
36111,The Midnight Club,James Patterson,Fiction,en
64193,Morning in the Burned House,Margaret Atwood,Poetry,en
61058,Public Secrets,Nora Roberts,Fiction,en
25382,The Dead Zone,Stephen King,Fiction,en
76329,Bluebeards Egg,Margaret Atwood,Fiction,en
16080,On Writing,Stephen King,Language Arts & Disciplines,en
63632,Prey,Graham Masterton,Fiction,en
36076,Anna Karenina,Leo Tolstoy,Fiction,en
58831,Photography Your Way,Chuck Delaney,Photography,en
14197,Lawless,Nora Roberts,Fiction,en
125525,The Rocky Road to Romance,Janet Evanovich,Fiction,en
4861,Firestarter,Stephen King,Fiction,en
78638,The Body in the Library,Agatha Christie,Fiction,en
93338,Deception Point,Dan Brown,Fiction,hi
106662,Dracula,Bram Stoker,Fiction,en
207674,Love,TONI MORRISON,Fiction,en
234605,Harry Potter and the Sorcerer's Stone,J. K. Rowling,"Children's stories, English",en
163686,A Time to Kill,John Grisham,Fiction,en

In [74]:
books_master.columns.tolist()

['ISBN',
 'Book-Title',
 'Book-Author',
 'Year-Of-Publication',
 'Publisher',
 'Image-URL-S',
 'Image-URL-M',
 'Image-URL-L',
 'title_clean',
 'author_clean',
 'match_key',
 'description',
 'categories',
 'language',
 'page_count',
 'thumbnail']

In [75]:
books_master = books_master.drop(
    columns=[
        "title_clean",
        "author_clean",
        "match_key"
    ]
)

In [76]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [77]:
ratings_master = ratings.rename(
    columns={
        "Book-Rating": "Rating"
    }
)

In [78]:
books_master.to_csv(
    "../data/processed/books_master.csv",
    index=False
)

ratings_master.to_csv(
    "../data/processed/ratings_master.csv",
    index=False
)

In [79]:
print(books_master.shape)
print(ratings_master.shape)

(271360, 13)
(1149780, 3)