In [1]:
import cv2
import json
import ollama
import pandas as pd

from pathlib import Path
from paddleocr import PaddleOCR
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import as_completed

In [2]:
ocr = PaddleOCR(
    use_angle_cls=True,
    lang="en"
)

[2026/06/12 16:12:25] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='C:\\Users\\anshu/.paddleocr/whl\\det\\en\\en_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\anshu/.paddleocr/whl\\rec\\en\\en_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='c:\\Users\\anshu\\Documents\\codes\\ML\\BookRecomendation\\.venv\\Lib\\site-packages\\paddleocr\\ppocr\\utils\\en_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='C:\\Users\\anshu/.paddleocr/whl\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='en', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')

In [3]:
def run_ocr(img):

    result = ocr.ocr(img)

    if not result:
        return "", 0

    if result[0] is None:
        return "", 0

    words = []
    confs = []

    for line in result[0]:

        words.append(line[1][0])
        confs.append(line[1][1])

    text = " ".join(words)

    confidence = (
        sum(confs)/len(confs)
        if len(confs)
        else 0
    )

    return text, confidence

In [4]:
def get_rotations(image):

    return {

        "original": image,

        "90_cw":
        cv2.rotate(
            image,
            cv2.ROTATE_90_CLOCKWISE
        ),

        "90_ccw":
        cv2.rotate(
            image,
            cv2.ROTATE_90_COUNTERCLOCKWISE
        ),

        "180":
        cv2.rotate(
            image,
            cv2.ROTATE_180
        )
    }

In [5]:
def get_best_ocr_text(image_path):

    image = cv2.imread(image_path)

    if image is None:
        return None

    rotations = get_rotations(image)

    best = None
    best_score = -1

    for name, rotated in rotations.items():

        text, conf = run_ocr(rotated)

        score = len(text) * conf

        if score > best_score:

            best_score = score

            best = {

                "text":
                text.upper(),

                "confidence":
                conf,

                "rotation":
                name
            }

    return best

In [6]:
def identify_book_with_gemma(
    image_path,
    ocr_text
):

    prompt = f"""
You are identifying a book from a bookshelf.

OCR text:

{ocr_text}

The OCR may contain severe mistakes.

Use BOTH:
1. The image
2. The OCR text

Most books belong to fantasy or science fiction authors.

Examples include:
Brandon Sanderson
Terry Pratchett
Anthony Ryan
Peter F. Hamilton
John Gwynne
Guy Gavriel Kay
Jay Kristoff
Andrzej Sapkowski
Ann Leckie
Alastair Reynolds

First reconstruct the likely spine text.

Then identify the exact book.

Return ONLY JSON:

{{
"title":"",
"author":"",
"corrected_spine_text":"",
"reasoning":"",
"confidence":0
}}
"""

    response = ollama.chat(

        model="gemma4:31b-cloud",

        messages=[
            {
                "role":"user",
                "content":prompt,
                "images":[image_path]
            }
        ]
    )

    return response["message"]["content"]

In [7]:
def parse_response(text):

    try:

        start = text.find("{")
        end = text.rfind("}") + 1

        return json.loads(
            text[start:end]
        )

    except:

        return {

            "title":"UNKNOWN",
            "author":"UNKNOWN",
            "confidence":0
        }

In [8]:
def process_spine(spine_path):

    try:

        best = get_best_ocr_text(
            spine_path
        )

        if best is None:

            return {

                "file": spine_path,
                "title": "UNKNOWN"
            }

        response = identify_book_with_gemma(

            spine_path,

            best["text"]
        )

        book = parse_response(
            response
        )

        return {

            "file":
            spine_path,

            "ocr":
            best["text"],

            "title":
            book.get(
                "title",
                ""
            ),

            "author":
            book.get(
                "author",
                ""
            ),

            "corrected_spine_text":
            book.get(
                "corrected_spine_text",
                ""
            ),

            "confidence":
            book.get(
                "confidence",
                0
            )
        }

    except Exception as e:

        return {

            "file":
            spine_path,

            "title":
            "ERROR",

            "error":
            str(e)
        }

In [9]:
spines = sorted(

    Path(
        "../outputs/book_spines"
    ).glob("*.jpg")

)

print(
    len(spines)
)

165

In [10]:
results = []

with ThreadPoolExecutor(
    max_workers=5
) as executor:

    futures = {

        executor.submit(
            process_spine,
            str(spine)
        ): spine

        for spine in spines
    }

    completed = 0

    for future in as_completed(
        futures
    ):

        completed += 1

        result = future.result()

        results.append(
            result
        )

        print(
            completed,
            "/",
            len(spines),
            result.get(
                "title",
                ""
            )
        )

[2026/06/12 16:12:26] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.1800248622894287
[2026/06/12 16:12:26] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.25654149055480957
[2026/06/12 16:12:26] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:26] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:26] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:26] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.13602423667907715
[2026/06/12 16:12:26] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:26] ppocr DEBUG: cls num  : 1, elapsed : 0.1315164566040039
[2026/06/12 16:12:26] ppocr DEBUG: rec_res num  : 1, elapsed : 0.12393522262573242
[2026/06/12 16:12:26] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.3379702568054199
[2026/06/12 16:12:26] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.10129165649414062
[2026/06/12 16:12:26] ppocr DEBUG: cls num  : 2, elapsed : 0.04451441764831543
[2026/06/12 16:12:26] ppocr DEBUG: dt_boxes num : 3, elapsed : 0.4032573699951172
[2026/06/12 16:12:26] ppocr DEBUG: cls num  : 1, elapsed : 0.04950594902038574
[2026/06/12 16:12:26] ppocr DEBUG: rec_res num  : 2, elapsed : 0.17667222023010254
[2026/06/12 16:12:27] ppocr DEBUG: rec_res num  : 1, elapsed : 0.2815842628479004
[2026/06/12 16:12:27] ppocr DEBUG: cls num  : 3, elapsed : 0.17602777481079102
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.06400442123413086
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 9, elapsed : 1.1070146560668945
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.06500434875488281
[2026/06/12 16:12:27] ppocr DEBUG: cls num  : 1, elapsed : 0.012001991271972656
[2026/06/12 16:12:27] ppocr DEBUG: rec_res num  : 3, elapsed : 0.22494864463806152
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 9, elapsed : 1.3299624919891357
[2026/06/12 16:12:27] ppocr DEBUG: cls num  : 1, elapsed : 0.21688437461853027
[2026/06/12 16:12:27] ppocr DEBUG: rec_res num  : 1, elapsed : 0.07978224754333496
[2026/06/12 16:12:27] ppocr DEBUG: rec_res num  : 1, elapsed : 0.12152457237243652
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.030510425567626953
[2026/06/12 16:12:27] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:27] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.20503783226013184
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 4, elapsed : 0.27988457679748535
1 / 165 ERROR
[2026/06/12 16:12:27] ppocr DEBUG: cls num  : 9, elapsed : 0.23255324363708496
[2026/06/12 16:12:27] ppocr DEBUG: cls num  : 9, elapsed : 0.2041316032409668
[2026/06/12 16:12:27] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.0785975456237793
[2026/06/12 16:12:27] ppocr DEBUG: cls num  : 4, elapsed : 0.0575106143951416
[2026/06/12 16:12:28] ppocr DEBUG: cls num  : 1, elapsed : 0.32055115699768066
2 / 165 ERROR
[2026/06/12 16:12:28] ppocr DEBUG: rec_res num  : 9, elapsed : 0.8312211036682129
[2026/06/12 16:12:28] ppocr DEBUG: rec_res num  : 4, elapsed : 0.5749001502990723
[2026/06/12 16:12:28] ppocr DEBUG: rec_res num  : 9, elapsed : 1.172487735748291
[2026/06/12 16:12:28] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.23903107643127441
[2026/06/12 16:12:28] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.018002986907958984
[2026/06/12 16:12:29] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:29] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:29] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:29] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:29] ppocr DEBUG: dt_boxes num : 4, elapsed : 0.2323167324066162
[2026/06/12 16:12:29] ppocr DEBUG: dt_boxes num : 6, elapsed : 0.47440457344055176
[2026/06/12 16:12:29] ppocr DEBUG: dt_boxes num : 4, elapsed : 0.10547614097595215
[2026/06/12 16:12:29] ppocr DEBUG: cls num  : 4, elapsed : 0.017000675201416016
3[2026/06/12 16:12:29] ppocr DEBUG: rec_res num  : 4, elapsed : 0.15052580833435059
 / 165 ERROR
[2026/06/12 16:12:29] ppocr DEBUG: cls num  : 4, elapsed : 0.14952683448791504
[2026/06/12 16:12:29] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.0685114860534668
[2026/06/12 16:12:29] ppocr DEBUG: rec_res num  : 4, elapsed : 0.13552618026733398
[2026/06/12 16:12:29] ppocr DEBUG: cls num  : 1, elapsed : 0.1640336513519287
[2026/06/12 16:12:29] ppocr DEBUG: dt_boxes num : 5, elapsed : 0.24554657936096191
[2026/06/12 16:12:29] ppocr DEBUG: rec_res num  : 1, elapsed : 0.12251520156860352
[2026/06/12 16:12:29] ppocr DEBUG: dt_boxes num : 4, elapsed : 0.262542724609375
[2026/06/12 16:12:29] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.08951759338378906
[2026/06/12 16:12:29] ppocr DEBUG: cls num  : 1, elapsed : 0.007055521011352539
[2026/06/12 16:12:29] ppocr DEBUG: cls num  : 5, elapsed : 0.05306267738342285
[2026/06/12 16:12:30] ppocr DEBUG: rec_res num  : 1, elapsed : 0.12100410461425781
[2026/06/12 16:12:30] ppocr DEBUG: cls num  : 4, elapsed : 0.18306827545166016
[2026/06/12 16:12:30] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.009999752044677734
4 / 165 ERROR
[2026/06/12 16:12:30] ppocr DEBUG: rec_res num  : 5, elapsed : 0.4565761089324951
[2026/06/12 16:12:30] ppocr DEBUG: cls num  : 1, elapsed : 0.08051228523254395
[2026/06/12 16:12:30] ppocr DEBUG: rec_res num  : 1, elapsed : 0.13698983192443848
[2026/06/12 16:12:30] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.2780148983001709
[2026/06/12 16:12:30] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.2780163288116455
[2026/06/12 16:12:30] ppocr DEBUG: cls num  : 1, elapsed : 0.037001609802246094
[2026/06/12 16:12:30] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.09951567649841309
[2026/06/12 16:12:30] ppocr DEBUG: cls num  : 2, elapsed : 0.07951760292053223
[2026/06/12 16:12:30] ppocr DEBUG: rec_res num  : 1, elapsed : 0.13602876663208008
[2026/06/12 16:12:30] ppocr DEBUG: cls num  : 2, elapsed : 0.14449691772460938
[2026/06/12 16:12:30] ppocr DEBUG: rec_res num  : 2, elapsed : 0.24100875854492188
[2026/06/12 16:12:31] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.19382762908935547
[2026/06/12 16:12:31] ppocr DEBUG: rec_res num  : 2, elapsed : 0.1945784091949463
[2026/06/12 16:12:31] ppocr DEBUG: cls num  : 1, elapsed : 0.013001441955566406
[2026/06/12 16:12:31] ppocr DEBUG: rec_res num  : 1, elapsed : 0.0725851058959961
[2026/06/12 16:12:31] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.009648561477661133
[2026/06/12 16:12:31] ppocr DEBUG: cls num  : 2, elapsed : 0.008460044860839844
[2026/06/12 16:12:31] ppocr DEBUG: rec_res num  : 2, elapsed : 0.0703420639038086
[2026/06/12 16:12:31] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.008999824523925781
[2026/06/12 16:12:31] ppocr DEBUG: cls num  : 1, elapsed : 0.00600123405456543
[2026/06/12 16:12:31] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05443453788757324
5 / 165 Wintersmith
[2026/06/12 16:12:32] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.016005754470825195
[2026/06/12 16:12:32] ppocr DEBUG: cls num  : 1, elapsed : 0.010005712509155273
[2026/06/12 16:12:32] ppocr DEBUG: rec_res num  : 1, elapsed : 0.06351590156555176
[2026/06/12 16:12:32] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.0834956169128418
[2026/06/12 16:12:32] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:32] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:32] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.009000539779663086
[2026/06/12 16:12:32] ppocr DEBUG: cls num  : 1, elapsed : 0.005999565124511719
[2026/06/12 16:12:32] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05475473403930664
[2026/06/12 16:12:32] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.010135650634765625
[2026/06/12 16:12:32] ppocr DEBUG: cls num  : 1, elapsed : 0.006879091262817383
[2026/06/12 16:12:32] ppocr DEBUG: rec_res num  : 1, elapsed : 0.04600167274475098
6 / 165 Legion of Flame
[2026/06/12 16:12:33] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.05594372749328613
[2026/06/12 16:12:33] ppocr DEBUG: cls num  : 2, elapsed : 0.010452032089233398
[2026/06/12 16:12:33] ppocr DEBUG: rec_res num  : 2, elapsed : 0.06508302688598633
[2026/06/12 16:12:33] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.07503104209899902
[2026/06/12 16:12:33] ppocr DEBUG: cls num  : 2, elapsed : 0.0060024261474609375
[2026/06/12 16:12:33] ppocr DEBUG: rec_res num  : 2, elapsed : 0.08452939987182617
[2026/06/12 16:12:33] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.00800013542175293
[2026/06/12 16:12:33] ppocr DEBUG: cls num  : 2, elapsed : 0.005002260208129883
[2026/06/12 16:12:33] ppocr DEBUG: rec_res num  : 2, elapsed : 0.07051825523376465
[2026/06/12 16:12:33] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.00699925422668457
[2026/06/12 16:12:33] ppocr DEBUG: cls num  : 1, elapsed : 0.010002851486206055
[2026/06/12 16:12:33] ppocr DEBUG: rec_res num  : 1, elapsed : 0.06051135063171387
7 / 165 The Hero of Ages
[2026/06/12 16:12:38] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.01602458953857422
[2026/06/12 16:12:38] ppocr DEBUG: cls num  : 2, elapsed : 0.012511253356933594
[2026/06/12 16:12:38] ppocr DEBUG: rec_res num  : 2, elapsed : 0.07663679122924805
[2026/06/12 16:12:38] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.013513565063476562
[2026/06/12 16:12:38] ppocr DEBUG: cls num  : 1, elapsed : 0.006851911544799805
[2026/06/12 16:12:38] ppocr DEBUG: rec_res num  : 1, elapsed : 0.052718162536621094
8 / 165 Good Omens
[2026/06/12 16:12:38] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.06658506393432617
[2026/06/12 16:12:38] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.06808304786682129
[2026/06/12 16:12:38] ppocr DEBUG: cls num  : 1, elapsed : 0.008511781692504883
[2026/06/12 16:12:38] ppocr DEBUG: cls num  : 1, elapsed : 0.0190277099609375
[2026/06/12 16:12:38] ppocr DEBUG: rec_res num  : 1, elapsed : 0.0585787296295166
[2026/06/12 16:12:38] ppocr DEBUG: rec_res num  : 1, elapsed : 0.19073724746704102
[2026/06/12 16:12:38] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.15018105506896973
[2026/06/12 16:12:38] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:38] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:38] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.09861159324645996
[2026/06/12 16:12:38] ppocr DEBUG: cls num  : 1, elapsed : 0.01155400276184082
[2026/06/12 16:12:38] ppocr DEBUG: rec_res num  : 1, elapsed : 0.1472032070159912
[2026/06/12 16:12:38] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.009513616561889648
[2026/06/12 16:12:38] ppocr DEBUG: cls num  : 1, elapsed : 0.007515430450439453
[2026/06/12 16:12:39] ppocr DEBUG: rec_res num  : 1, elapsed : 0.13862848281860352
[2026/06/12 16:12:39] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.008512020111083984
[2026/06/12 16:12:39] ppocr DEBUG: cls num  : 1, elapsed : 0.0045049190521240234
[2026/06/12 16:12:39] ppocr DEBUG: rec_res num  : 1, elapsed : 0.08460545539855957
9 / 165 The Naked God
[2026/06/12 16:12:44] ppocr DEBUG: dt_boxes num : 3, elapsed : 0.06215381622314453
[2026/06/12 16:12:44] ppocr DEBUG: cls num  : 3, elapsed : 0.0525660514831543
[2026/06/12 16:12:44] ppocr DEBUG: rec_res num  : 3, elapsed : 0.14615273475646973
[2026/06/12 16:12:44] ppocr DEBUG: dt_boxes num : 4, elapsed : 0.10914254188537598
[2026/06/12 16:12:44] ppocr DEBUG: cls num  : 4, elapsed : 0.03867292404174805
[2026/06/12 16:12:44] ppocr DEBUG: rec_res num  : 4, elapsed : 0.1849043369293213
[2026/06/12 16:12:44] ppocr DEBUG: dt_boxes num : 4, elapsed : 0.00851130485534668
[2026/06/12 16:12:45] ppocr DEBUG: cls num  : 4, elapsed : 0.008515119552612305
[2026/06/12 16:12:45] ppocr DEBUG: rec_res num  : 4, elapsed : 0.10382294654846191
[2026/06/12 16:12:45] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.00851297378540039
[2026/06/12 16:12:45] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:45] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
10 / 165 A Brightness Long Ago
[2026/06/12 16:12:47] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.056565284729003906
[2026/06/12 16:12:47] ppocr DEBUG: cls num  : 2, elapsed : 0.04828333854675293
[2026/06/12 16:12:47] ppocr DEBUG: rec_res num  : 2, elapsed : 0.11113524436950684
[2026/06/12 16:12:47] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.07806944847106934
[2026/06/12 16:12:47] ppocr DEBUG: cls num  : 2, elapsed : 0.004506349563598633
[2026/06/12 16:12:47] ppocr DEBUG: rec_res num  : 2, elapsed : 0.07158994674682617
[2026/06/12 16:12:47] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.007510662078857422
[2026/06/12 16:12:47] ppocr DEBUG: cls num  : 2, elapsed : 0.005512237548828125
[2026/06/12 16:12:47] ppocr DEBUG: rec_res num  : 2, elapsed : 0.10361433029174805
[2026/06/12 16:12:47] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.009018182754516602
[2026/06/12 16:12:47] ppocr DEBUG: cls num  : 2, elapsed : 0.006510496139526367
[2026/06/12 16:12:47] ppocr DEBUG: rec_res num  : 2, elapsed : 0.0771644115447998
11 / 165 A Small Favor
[2026/06/12 16:12:50] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.0829310417175293
[2026/06/12 16:12:50] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:50] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:50] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.09551405906677246
[2026/06/12 16:12:50] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:50] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:50] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.007502555847167969
[2026/06/12 16:12:50] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:50] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:50] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.008002519607543945
[2026/06/12 16:12:50] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:50] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
12 / 165 Men-at-Arms
[2026/06/12 16:12:51] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.058008670806884766
[2026/06/12 16:12:51] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:51] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:51] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.09186053276062012
[2026/06/12 16:12:51] ppocr DEBUG: cls num  : 1, elapsed : 0.0439610481262207
[2026/06/12 16:12:52] ppocr DEBUG: rec_res num  : 1, elapsed : 0.09252381324768066
[2026/06/12 16:12:52] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.010538101196289062
[2026/06/12 16:12:52] ppocr DEBUG: cls num  : 1, elapsed : 0.009366989135742188
[2026/06/12 16:12:52] ppocr DEBUG: rec_res num  : 1, elapsed : 0.06494283676147461
[2026/06/12 16:12:52] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.008656978607177734
[2026/06/12 16:12:52] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:52] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
13 / 165 Revelation Space
[2026/06/12 16:12:54] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.05453085899353027
[2026/06/12 16:12:54] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:54] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:54] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.09888648986816406
[2026/06/12 16:12:54] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:54] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:54] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.008001327514648438
[2026/06/12 16:12:54] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:54] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:12:54] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.008999824523925781
[2026/06/12 16:12:54] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:12:54] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
14 / 165 Tailored Realities
[2026/06/12 16:12:56] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.013988971710205078
[2026/06/12 16:12:56] ppocr DEBUG: cls num  : 1, elapsed : 0.01000070571899414
[2026/06/12 16:12:56] ppocr DEBUG: rec_res num  : 1, elapsed : 0.059519052505493164
[2026/06/12 16:12:56] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.014000654220581055
[2026/06/12 16:12:56] ppocr DEBUG: cls num  : 1, elapsed : 0.006002187728881836
[2026/06/12 16:12:56] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05100226402282715
[2026/06/12 16:12:56] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.00700688362121582
[2026/06/12 16:12:56] ppocr DEBUG: cls num  : 2, elapsed : 0.0355076789855957
[2026/06/12 16:12:56] ppocr DEBUG: rec_res num  : 2, elapsed : 0.08752298355102539
[2026/06/12 16:12:56] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.007999658584594727
[2026/06/12 16:12:56] ppocr DEBUG: cls num  : 1, elapsed : 0.006000518798828125
[2026/06/12 16:12:56] ppocr DEBUG: rec_res num  : 1, elapsed : 0.053003549575805664
15 / 165 Thief of Time
[2026/06/12 16:12:57] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.013998746871948242
[2026/06/12 16:12:57] ppocr DEBUG: cls num  : 1, elapsed : 0.007264852523803711
[2026/06/12 16:12:58] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05800437927246094
[2026/06/12 16:12:58] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.013003110885620117
[2026/06/12 16:12:58] ppocr DEBUG: cls num  : 1, elapsed : 0.006508827209472656
[2026/06/12 16:12:58] ppocr DEBUG: rec_res num  : 1, elapsed : 0.053003549575805664
[2026/06/12 16:12:58] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.00800013542175293
[2026/06/12 16:12:58] ppocr DEBUG: cls num  : 1, elapsed : 0.005000591278076172
[2026/06/12 16:12:58] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05288124084472656
[2026/06/12 16:12:58] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.008000612258911133
[2026/06/12 16:12:58] ppocr DEBUG: cls num  : 2, elapsed : 0.009001970291137695
[2026/06/12 16:12:58] ppocr DEBUG: rec_res num  : 2, elapsed : 0.07851386070251465
16 / 165 The Shadow of the Torturer
[2026/06/12 16:13:00] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.02137017250061035
[2026/06/12 16:13:00] ppocr DEBUG: cls num  : 1, elapsed : 0.01099848747253418
[2026/06/12 16:13:00] ppocr DEBUG: rec_res num  : 1, elapsed : 0.047003746032714844
[2026/06/12 16:13:00] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.007003068923950195
[2026/06/12 16:13:00] ppocr DEBUG: cls num  : 1, elapsed : 0.007001638412475586
[2026/06/12 16:13:00] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05251479148864746
[2026/06/12 16:13:00] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.00700068473815918
[2026/06/12 16:13:00] ppocr DEBUG: cls num  : 2, elapsed : 0.01000070571899414
[2026/06/12 16:13:00] ppocr DEBUG: rec_res num  : 2, elapsed : 0.0778958797454834
[2026/06/12 16:13:00] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.0069997310638427734
[2026/06/12 16:13:00] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:13:00] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
17 / 165 The Blood-Crown of Conan
[2026/06/12 16:13:01] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.01401209831237793
[2026/06/12 16:13:01] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:13:01] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:13:01] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.0076944828033447266
[2026/06/12 16:13:01] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:13:01] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:13:01] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.009046554565429688
[2026/06/12 16:13:01] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:13:01] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:13:01] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.00925588607788086
[2026/06/12 16:13:01] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:13:01] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
18 / 165 The Path of Daggers
[2026/06/12 16:13:04] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.05077505111694336
[2026/06/12 16:13:04] ppocr DEBUG: cls num  : 0, elapsed : 0
[2026/06/12 16:13:04] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
[2026/06/12 16:13:04] ppocr DEBUG: dt_boxes num : 3, elapsed : 0.07049846649169922
[2026/06/12 16:13:04] ppocr DEBUG: cls num  : 3, elapsed : 0.04150700569152832
[2026/06/12 16:13:04] ppocr DEBUG: rec_res num  : 3, elapsed : 0.1566479206085205
[2026/06/12 16:13:04] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.0075113773345947266
[2026/06/12 16:13:04] ppocr DEBUG: cls num  : 1, elapsed : 0.011245012283325195
[2026/06/12 16:13:04] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05122637748718262

In [11]:
df = pd.DataFrame(
    results
)

df.head()

,file,title,error,ocr,author,corrected_spine_text,confidence
0,..\outputs\book_spines\spine_101.jpg,ERROR,(PreconditionNotMet) Tensor holds no memory. C...,NaN,NaN,NaN,NaN
1,..\outputs\book_spines\spine_102.jpg,ERROR,index 1 is out of bounds for axis 0 with size 1,NaN,NaN,NaN,NaN
2,..\outputs\book_spines\spine_0.jpg,ERROR,(PreconditionNotMet) Tensor holds no memory. C...,NaN,NaN,NaN,NaN
3,..\outputs\book_spines\spine_103.jpg,ERROR,index 4 is out of bounds for axis 0 with size 4,NaN,NaN,NaN,NaN
4,..\outputs\book_spines\spine_100.jpg,Wintersmith,NaN,KEINSRZLNLA,Terry Pratchett,WINTERSMITH Terry Pratchett,1.0

In [12]:
df.to_csv(

    "../outputs/detected_books.csv",

    index=False
)

print(
    "Saved",
    len(df),
    "books"
)

Saved 165 books

In [13]:
df[
    [
        "title",
        "author",
        "confidence"
    ]
].sample(
    20
)

                       title                               author  confidence
69        The Grace of Kings                              Ken Liu        0.90
124                The Truth                      Terry Pratchett        0.90
31      The Eye of the World                        Robert Jordan        0.95
72             The Last King                    Robert F. Gilbert        0.70
94                    Tigana                      Guy Gavriel Kay        1.00
13        Tailored Realities                    Brandon Sanderson        1.00
91        Mother of Learning                      Domagoj Kurmaic        1.00
138  The Strength of the Few                      James Islington        1.00
99        The Fifth Elephant                      Terry Pratchett        1.00
164          Moving Pictures                      Terry Pratchett        1.00
2                      ERROR                                  NaN         NaN
5            Legion of Flame                         Anthony Ryan        1.00
27        Towers of Midnight  Robert Jordan and Brandon Sanderson        1.00
33     The Archimedes Engine                    Peter F. Hamilton        1.00
68                   Unknown                              Unknown        0.00
111    A Night Without Stars                    Alastair Reynolds        1.00
79             The Book That                        Mark Lawrence        0.90
93               The Witcher                    Andrzej Sapkowski        1.00
129                    Jingo                      Terry Pratchett        1.00
118    The Nightmare Painter                    Brandon Sanderson        1.00